replicaCount: 1

image:
  repository: linuxserver/sonarr
  tag: 4.0.17.2952-ls314
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8989

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: "retain-default-storageclass"
    dataPath: /config

volumes:
  tv:
    hostPath: /mnt/nas/tv
    mountPath: /tv
  downloads:
    hostPath: /mnt/nas/data/completed
    mountPath: /data/completed

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "Etc/UTC"