apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - tunnel
          - --no-autoupdate
          - run
        env:
        - name: CFDPATH
          value: /etc/cloudflared
        - name: LOG_LEVEL
          value: {{ .Values.logLevel }}
        - name: LOG_FILE
          value: {{ .Values.logFile }}
        volumeMounts:
        - name: cloudflared-pem
          mountPath: /etc/cloudflared
          subPath: cert.pem
          readOnly: true
      volumes:
      - name: cloudflared-pem
        secret:
          secretName: {{ .Values.secretName }}
