replicaCount: 1

image:
  repository: qdrant/qdrant
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 6333
  loadBalancerIP: 192.168.2.23

persistence:
  enabled: true
  storagePath: ./qdrant-storage  # Path relative to the Helm chart
  mountPath: /qdrant/storage
  accessMode: ReadWriteOnce
  size: 1Gi