apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sitemark-db-secret
  namespace: sitemark-api
spec:
  encryptedData:
    password: AgAwjfcpFIKFbsCnmZw/yud5Az/E6BV2HZQ9KB0ojC8R/D7chC27zthgkP0nQ6pUHwVG+Gtzfc+W8WJCN/bsmo2ipjwh/cw+B1WIRnWvVXgc9G+L6NqQQM3BMqjmo4RY/v6BeGq+0cENwuyrYnLtReimG7FJA3wm6Pcy7ZcrdvtQ7tUOmmB2kZgQDZuRWvlPNXSOMLyCQyY+rzJTfruNeIuUa89BfSubbQ5XBC35Q1jBubYdVO40v08FgTKo9M5rfAI9DQPp10h0NW/dTg77tOVFAHOzcvp+kS6DscYiUU9NMLAIqc7S0ItGNhtKj+25nGcYBpuyvqRI2tbgsfIV6jp/cwLPAu0hQD7pCyrTfJnhSlJ+npfnSuhy5VQ82bPQzsx/Ga5PaoQpx4k5mZGvWpNsUr4bhaGo3yMFTVVCsTIUHMI8KmNOku2ZJrU2HicxMeP4k7C5UyFealb8cahVSPV5xyS0j0TIgdYnr4CTa5IUFQQ0sEogxVyd7WsuHawurycvN+79j/wyumd704LBS+AU6pywrNYimDap3VVcWXXc7cKgeeZAfaQIvWH99IFZMAdmCXzGx1XmRt5BAycRAl3xqbqmGVDm3MxRJF1Sze2/G2MrU8UW5+xrdZACQaf4P890ExQzJbitLQbJZUL3WypvhWVV+OcE8nK961wWasWpWF9maEFhu0+maw0QzrkwdLbERJwIyoBaIFe2Y/InWX5waI4hqnvuScRlQ6NWbDDHtIxoBYWkSydFfrUxZOdARdQ=
  template:
    metadata:
      creationTimestamp: null
      name: sitemark-db-secret
      namespace: sitemark-api
