apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sitemark-db-secret
  namespace: sitemark-api
spec:
  encryptedData:
    password: AgAYPsip2Imql5OgiaZqzNimV8Fb/fgdQlUreI0RBZSGUa3wV/VC2SiB1e3GHfpRTfFoWQ63Tef+tiLMfhEMpTGaMcTxyJS/i3ltOw75kk2KRJoNucqbgZuZdbXMOHWW+1UxIEfgthUAD1mkwqzbrmCruWXdeh3SX1RcdnZlcx0cQowILqiSiS6vgw064TH3f1NWIh56FU8wcchvX7kCebhA1PMEiO0TkxU+j2OfxYDrh/E/gfrbzP0+GbvFPQNwhKwrag+cPCmk51yuqw6MZ38gFIvo2ZJSmbBrh9OqLdfIoQkcNkW3ydO3tF+S3jgA9tZe8xEvAqD+8aGPB7YdPLhWYj02LhDYbKxTAXmMlzTARgc4uwueJ6og+YCad9MzTV+G7ghvifS4+nIGtY/ZQXlT9EbwGPKGV0l8nlFf302tE7HPJbmQW+a5S6uyTARTQG/L/r110D2tvMx73nqUmU7tKiBROF41mzAU7MB2zYN4OrYZBdWegeJHLzOljJwgiNJEEpYjuAkrHI9GFk0NJREPIwMC0+w2SYDPaD6EjbcadY6nspsxkfR6UISZVZYeEqDTkYqOkBZnZAmPzBh153Xyln37vTLGBD7pTaPOEnT+ADx9HvI5ce9h44SPeks5KxzMhl8O/K2c07Mh3XQpdcJPgwSivlFQsPA7y2zSSFiqq+LQUp3QhK5eSuci6cOLkp5k8Qh+5Awim97/MIFi6WTAXOCJYYqwp28v0bFZcccd84NnTy7qg1tNjg7P3g==
  template:
    metadata:
      creationTimestamp: null
      name: sitemark-db-secret
      namespace: sitemark-api
