apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitemark-api.fullname" . }}
  namespace: sitemark-api
  labels:
    {{- include "sitemark-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "sitemark-api.name" . }}
