apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 8123
        env:
        - name: TZ
          value: "{{ .Values.env.TZ }}"
        volumeMounts:
        - name: home-assistant-config
          mountPath: /config
      volumes:
      - name: home-assistant-config
        persistentVolumeClaim:
          claimName: home-assistant-config
