image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 11434

persistence:
  enabled: true
  size: 10Gi
  storageClass: local-path
  mountPath: /root/.ollama

gpu:
  enabled: true
  runtimeClassName: nvidia
