image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  port: 11434
  loadBalancerIP: 192.168.2.22

persistence:
  enabled: true
  size: 10Gi
  storageClass: local-path
  mountPath: /root/.ollama

gpu:
  enabled: true
  runtimeClassName: nvidia
