apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin.fullname" . }}
  namespace: jellyfin
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jellyfin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: jellyfin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
          volumeMounts:
            - name: config
              mountPath: {{ .Values.persistence.config.mountPath }}
            - name: tv
              mountPath: {{ .Values.volumes.tv.mountPath }}
            - name: movies
              mountPath: {{ .Values.volumes.movies.mountPath }}
          {{- if .Values.gpu.enabled }}
          resources:
            limits:
              nvidia.com/gpu: 1
          {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.fullname" . }}-config
        - name: tv
          hostPath:
            path: {{ .Values.volumes.tv.hostPath }}
        - name: movies
          hostPath:
            path: {{ .Values.volumes.movies.hostPath }}
