apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin.fullname" . }}
  namespace: jellyfin
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jellyfin.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.gpu.enabled }}
      runtimeClassName: nvidia
      {{- end }}
      initContainers:
        - name: wait-for-nas
          image: busybox
          command: ['sh', '-c', 'echo "Checking NAS mount..."; until mountpoint -q /host-mnt-nas; do echo "NAS not mounted, waiting..."; sleep 5; done; echo "NAS is mounted."']
          volumeMounts:
            - name: nas-check
              mountPath: /host-mnt-nas
              mountPropagation: HostToContainer
      containers:
        - name: jellyfin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "{{ .Values.env.NVIDIA_VISIBLE_DEVICES }}"
          volumeMounts:
            - name: config
              mountPath: {{ .Values.persistence.config.mountPath }}
            - name: tv
              mountPath: {{ .Values.volumes.tv.mountPath }}
            - name: movies
              mountPath: {{ .Values.volumes.movies.mountPath }}
          {{- if .Values.gpu.enabled }}
          resources:
            limits:
              nvidia.com/gpu: 1
          {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.fullname" . }}-config
        - name: tv
          hostPath:
            path: {{ .Values.volumes.tv.hostPath }}
        - name: movies
          hostPath:
            path: {{ .Values.volumes.movies.hostPath }}
        - name: nas-check
          hostPath:
            path: /mnt/nas
