apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyfin.fullname" . }}-config
  namespace: jellyfin
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
