apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
        - name: wait-for-nas
          image: busybox
          command: ['sh', '-c', 'echo "Checking NAS mount..."; until mountpoint -q /host-mnt-nas; do echo "NAS not mounted, waiting..."; sleep 5; done; echo "NAS is mounted."']
          volumeMounts:
            - name: nas-check
              mountPath: /host-mnt-nas
              mountPropagation: HostToContainer
      containers:
        - name: transmission
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OPENVPN_PROVIDER
              value: "{{ .Values.openvpn.provider }}"
            - name: OPENVPN_CONFIG
              value: "{{ .Values.openvpn.config }}"
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sealedSecret.usernameSecretName }}
                  key: openvpn-username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sealedSecret.passwordSecretName }}
                  key: openvpn-password
            - name: LOCAL_NETWORK
              value: "{{ .Values.openvpn.localNetwork }}"
            - name: PUID
              value: "{{ .Values.openvpn.puid }}"
            - name: PGID
              value: "{{ .Values.openvpn.pgid }}"
          ports:
            - containerPort: 9091
          volumeMounts:
            - mountPath: "{{ .Values.persistence.mountPath }}"
              name: data
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: data
          hostPath:
            path: "{{ .Values.persistence.path }}"
        - name: nas-check
          hostPath:
            path: /mnt/nas
