apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openvpn-username
  namespace: default
spec:
  encryptedData:
    openvpn-username: AgCRK/y1t855qHyymkDltOMydHnmEb8rL/WQ02DaCbRHDxjGjKxYUSUCJ8tUs359D948/S/8ljkAVCvyXmpqrD2aC7eOaFRFkmEl4tCN8hFS2t2qeWq5uYOZUibx9wRSeN03/8n7VPjR9s8PyvKItGAb6t0BKsuzEAwwNyf4ZyDhG7odkjprZLd/cwXsPt9QpBjbVQSxDFkAFmS8yq2dfvaj07EHH7Yqc221tUK4R67X0mMoe7cP11nxAykU2V6XZFmUcf9CWa6K/7tlqiRzJqNOU8r7eskcYXbOOgn7XaH/OLGUl0w05GudJF8a41ZZqGg/q5+KjZdD6jm9piiiUjanqYGGnVOeAsYV/CK5amBk+65Jz2/7RXGnjr++3Cedw7tCRjqcJ/CNLs9m2q3BJReIawxLyY42vOrE17Ng1tC64e2BoANdU+HnM2rjXwARm/XIVcFfkV5Ebr+nkevasQNJ4TcjeWdLWOQfl724iZ9Lrcf9r6HE4CWJPENuRLpdIAu9ZTFWiYorSdjSqcoFaYXMoSN0UXpcnuOTVDcNi5Kn6g5DT8lKF4lTLslOIsCnaJtFOY51DYsEZeoYHtBNgOa7mJFpqNLli6HDb9TUbSzg2fbNQd4F3boskV0aVqNmobOcYMUUh9d5bKZHnZQEejI3XzJ69nNUBsPyt1V9FhkZ8LF6ERMKlDm4XidjzPIPnTaP456KzYM0Fw==
  template:
    metadata:
      creationTimestamp: null
      name: openvpn-username
      namespace: default
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openvpn-password
  namespace: default
spec:
  encryptedData:
    openvpn-password: AgAKdCqD+rCFqfPEE94TAQulf5kRyTcFcIBn8qY1/maD+bzWkYrZnFz/uDOinVhqErsHPSxMb6ZaOxUIP7p0maLsDFbJP5p1UU1qfbNoyZU+jQ2xwi1dNVuGNyqrx0fqC6bQumtne0IW+qpXYpjv3y7jL5wZvHuqkTwkJK56zwj7LYrA1pKVYjhNEQTwKAD8zjl8gcGwkacyLuGaz2a0aKx0xrG05CYvCPyTi2vHbabbQv+Sg90m+Qe+3lh8XsPeMoBa0kTuBmLoSST1RJNwr2YteyOoWHNp9bY68dCGltEbQQzENuzoP5bwQwOej04hjAYObO6//6zKfNOyISGtoEN9qf7H4eYQTk8CwefX0Ebfel0Q1Rp/ipVdha6abYyBt4BNwjfzrvOLCbWIGNlT8UqfafZiAXK9KH9+y1lgrt1nuKMKJm0pehWE2RaVkMBsmJA8jkQoTS3WR9bbd+jfknkqNdv5FB7ai0Znh1NRG2Uqv0kpMkU3Yfpvpd5k1i3yd9nKfrtRP5DquNKkhQBllzErhvdpUByyKjeIV8YNISqjUGIPwA1EVcvTwxV+SQ1cQ5atQ/2O90UeXSRcFrLq8Mn6qTfnyF17C9Xn2isf5Av5w8m0R71bl2+EIqFzHMzb3rRM+B+SDUvXcjrQWfPUrZ0RnzmiasH8OsOQkQpwtbBwRg5Q7QGxquEsoUs539oc9Wag2i43iNegKHCT
  template:
    metadata:
      creationTimestamp: null
      name: openvpn-password
      namespace: default