apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openvpn-username
  namespace: default
spec:
  encryptedData:
    openvpn-username: AgB0BTBUPnf3HNtMT8e4Y/Fc8rGUagSUf4qKHc3s3gYWkuMBPdw/FMX0xwxpNOu9mNq+nq40JcJszpEHshkzLaSGOa0ScqhITmH/edTyMIQq6/LQP+oPt7M+p8sf+XLM766dHc5xMNLzldyfuPZecGMplilFo0OC/POxLQfRcrkvEH2LICeSHk3npOJgMVOP1/JLuWm4xb5e6vjMWOuDLJolFilA3Gkh3THao1PxtsbOy2Znp4ikRGNX4/4nEMKBuk+TIU379pr/CbXHLlPVC2s/mfNWW0TLTfGWCObAj8U0daElWR/DRkhYU04O4MV/x348AAAuHJVh4RtoIi/E7hUQkeMm1jIyPD2cis608LHHYhR8oX03SY1uhTHsaR9FuiP99OjOxduEp4uBy+RFxMbjRZC8fN2VNkewifYTjsnjeTWN7b8jUT7aUmyL9QG9qU6LAqlnTQaROPEayvRfnGiJX0tL+2zMeyL1Gew/+hAE68E9EMsNud6Bo3qq3OHq0TUXap8tf610bVdPdpmnZFC9lAlv8fvnhPUZ7zLE0yiqrlG5/F4U9vbL72zIGugcNolcizwgEsLIOz+38b43qrydGiK6/MOjzeqfwIQdoekZof3mkO3SFPZyfYLzpM6EkWLBzCv9b9G5Zgvu++yGKEJFku5JPuLRUkHW57ugMjvvn/pxO3rhAdU5SnEu7fR9qLxBx43dq3UJIg==
  template:
    metadata:
      creationTimestamp: null
      name: openvpn-username
      namespace: default
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openvpn-password
  namespace: default
spec:
  encryptedData:
    password: AgBTqZnV2JJoP9qgCdcRmsU/qUAD01F6jiOcGe+umbSTHL13l/c2iYsngMOUyh1KqLa4C5q48tbUa5VguEvrOaEuRlSjUmT4ZXYjNnPIYVVf/Iukv3E9SXwKI/KTGNIkcx/y59Ks6AJYTZAhJtvRscyquQUulUn8csMqAKiWcVDAYUij5jKlNryQvCzradtmMlLzbcrld+/eOjRc9YSfV7lUzlwZ4w2D/pIxwF5bvE1MIaGzdRJBvDpXYUxjRw2avfD4T8+IlX2PVqOfN/ZsMbKDNLoV5i1cxZbeSUSEuN6IbJ8u4PmZp8rzzolSBUr+IQjdXwQuyq6Hc93afiZy4Ffqxkc1K3pSqNMpvJeQNReTyx+VFf51tuZIADRsH7aST2ifE43m4Rbm2Rz2n03aZDOlaZ2DZvZMO2pBALabmHP37PTHDJNRfNJukMLeUVOWXzzUAX1bOOYfWfBi7h7KaF91wxYNjCHjRcEcMq3VKrN6L9Nlxunu3aJfcW7sU6KbVAdQ4RiD1+iVqwN+4RlCiWz/BzOy/8G7NidSF15iOD5IoRM5RqHqQ4S0JpHjF64Dbz8Hp+N6J+qsAh3rergajQm/VhIvf63uC8QcALwWOERlBHxsh32pupUqLxSuDLtuigtj/0EGzZBJQzTNHF2D5pe2cnvI37kt0kTpnu1XL4Oj73bPCQayTLlKXQs3nck8xI1oyqS5uM6xFuQa
  template:
    metadata:
      creationTimestamp: null
      name: openvpn-password
      namespace: default