apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openvpn-username
  namespace: default
spec:
  encryptedData:
    username: AgCBvVZ9jsGk5fU+WFxx3hx4lftn48XYDLN3LB51pMSeF8wz4L7MPmAtjS5/pJdUO33DY458Udf4aJX2MdBD3PxdAwrkOPBMec/eoJjefT3rObc0NLi7n3jj0w9CojH2hPISV4WvBReKskHydar9XdiGGSrIdu+uRfxO9Vg2dLWMF+TZM3crUe6TGNen2qFXhMLdZXfgaJlCK1msspkNFvXJZz24cW58V905xENKD6cwrp7beXhxhBfIyyxsDRRiSzZYI7UQaqYBI8FoTtgTJsAdaWfwCNeVF019+484Qwp1Vwi6ycYRuAzHWmtnU3Gxlu+6DOAqQ1FDeYp8ufM9/zSZgEk4nVLKc99HdXB5qiPeyl/wsoTGDlcvWO//jWihDFhnx92jmgf+Bccn+GqFHwN8WACmretGR1bDXXG4W8OhJHGi4QMsCHCgV+hnR8fEZupeGqGP5EGZoC25XDdVngUqhN77lGAUb5oN14iQ2gLx9/Obarn5CZi3uxDaj73GRTuEk7OV2vm2PqGZ7GVjhG/IDp0z7+Uesi9MErneH/MUYiNb9KY3sJJ1nw1kKsUT08PbH2SUBven9XNmZOddevaJOgJGQuLJADcL2CdFgBpnLmkTKFtya4Xt8Vrx7BtcSdhj1RMRKsQSfWIm6I6OdYdlaugqR8ytm2PcUqVB53ST7J5x3myyemLF2pBKAP8ldQ2ffxFWWn/2d6pK
  template:
    metadata:
      creationTimestamp: null
      name: openvpn-username
      namespace: default
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openvpn-password
  namespace: default
spec:
  encryptedData:
    password: AgAleKdkkr+01rPosJIIm7nef6CbRyut027hzyyqXvbBpHDJUbgctcsDG9yCmfbNq7GYlYA7JB8xqlgE67zZ0pomVv1YMzjXybWeYLHXJTwtoNwVeS6hHtVOqaxFYlRJcWE0QbRRwF3Y4/Bk9YqC2kYEu/EbkpMDJdyi7GP3hFW8ZSucDAo6V9ixC6MvkjJWSy022tFUSt1fmOIWhw2bsAvFK3OY4Ywma3i7SP4d89qOy5Wl1u64IQUWk+B6jU/Ck6uzZvD+IRC+Lhwn3wILXosCgpO9MnKBXorN1oz302uuxXEH1WTBMTHN+/eYKkiD8k4vP8gzOO7GSl21BVgx5aOCZ+53STUKyzvXVNuigJF4+gUWnXC6FlhwK1U0WONbZjwXfG5P7csI5u4pW2OpPkSsF9Ei1LkcS2V8KSfOA8IizwU8feM9Rt4BkIqm4361sRtCpEes2jr6juk6S0qoeIud+5F6R3gZvlhDPm0gsQYnZLdO8FYAhUVlVpbeCCaX7vsOQlXD46JWAxHH7OuHSrTmqY1zi03X0d3tSFqIkSxW+8Z85hGb+9VMOR6mfq7n0OFPDZCJeeFiAtG6UUvcVAB+rAXkQd4WzJeaG6zNsnziyVimCvWoA4YF/c04KbGJyo1nOUFgy9RyKGJKPlZXBu42XFeX5ierHi/IoDXLrnU4hg5DgAK4O7HTGftqkMujsJyjkyMupTWLQ+FQ
  template:
    metadata:
      creationTimestamp: null
      name: openvpn-password
      namespace: default
