apiVersion: v2
name: jellyfin
version: 0.1.0
description: A Helm chart for deploying Jellyfin Media Server
type: application
appVersion: "latest"
sources:
  - https://jellyfin.org
  - https://hub.docker.com/r/linuxserver/jellyfin
