apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traceroute
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thatsimonsguy/homelab-k8s.git
    targetRevision: main
    path: apps/traceroute
  destination:
    server: https://kubernetes.default.svc
    namespace: traceroute
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
