apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ismatthealthy-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.persistence.storageClass }}
