---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ismatthealthy-r2
  namespace: ismatthealthy
spec:
  encryptedData:
    access-key-id: AgA57e78Ljn4jzBMsmjJddAUcfY+LktfdnHFrCqmdvo5/9BBvdwuJSsIs5PwMYOjW/b82O3K0myv41KmWLob21WRao4k/UNRfFhTjbgyv8BvinFKBe1hiNI2TC61adz8jqp1aNTWM283/g2ValmLH5tPP37ubV07XuMRNQQk4Kv8KDo0TP/cgPhEOQWPAa7UvBY71VQkUFy/tZ0LkxQSvQ7CQ+o3EoDIce+fR4RuFXKU8kL7o90jRauWusIcYdUtaeM/S+6VBtYFxKn43wygF3DsG8RXKLGKkXnA9z9xlEKWoa9FqIXBR8Qzp1y+VPrVTwb80PRy6rHX7qPpKaj9EhHTuJJP0Iz4lPXclcfEtCLAlXRpaV/23X6eY685CrbMGsL4p+WguOFIfSvKjQ8juXr0E/es1tb/WwnoiUZhwkekkiXKSwHn0NrRNPe1UfElmYq/0CumYxSnGujKvawDh/S4a4awZ9V5rDfsOKj+GLDFOk79BSzXn6ZmaB52jQ+l0hW72NbfZqPIih0bI8h0iNSfztf9/CmhX9k7oluqiWrl9nBTuZe8A97fLpENa70BOPRDY6oImFyDsFE0Ca/nW3J2evK4oass2daWA2D16Z4BlR8Qap/vaV77GDAbjVaOHED996zqMZk/cSy0vnMPjlTEIoAunAfqdWc31OF5hirNC9q6tme9a83b4zrupflge1Ac/nrB3c+/vJyPsQzD10DNs744u7Cnsi7GM09E0364SQ==
    secret-access-key: AgAqCUYzs1b7Qs+/S64syPgqORhTgvVT1zYq0aSuzuA/uuJWjLXTQIPc1gQbW0XwKh6uIQZH0qOTIBZiO3UapqkcT+MK6/c3/3MltxTCmTLu6IgyFkupTnjLObrohbdpdi2qbYHpqTbmNLyCpcM4ufC2piSTziV9a7A5+eHW0oPGl7ket4takt+NZqgo5F9+c/28juKdon+eTpz6HFNTJy/da7cCUoyf7G9Kvn9SX7cyLiTVBIBFYQtglw5dJqy0dhfzEI+v74z3ya3nxeYqlp3effZCkClua4DTrY7PuZpK3WCd7VtgwuCDZS4AGoFBkb1GNYEf70Jyqppmsj9z9FFT7M/FwXzO3eZS1YKdN83MgXrGH8m8YQx+Xd7ZQZI/+Z1zE41sMLXfY827LhJOtJINnomSRx4DSp6FSNiVFKkZI4GjlGmfWrfVS43j4psw0A1OEFsihMtmp8fcteWszZcWrKxOyNolxytvSWJKsDktikhczYk/oKxphUBv4GZozcs/hJzJ/pHbioFn/YMuS6KsZ6EspcIsL0CMDD0Cm8rM8AU3/9s9Pm6/7hL9ehhQSmka2OGRc+rgKoWM4ZUQwzcS9XTblgHSrCrmaA9BA0n3QBdy6CCfl7DCmM8xcumopV8u503+I/MyHA6LfaBbB+1Jzc4L5OG/vnQI2F+Dw1Gbq3QLgiPkPB2CpDfaHHGfK/Q/AeA2mEvIq1P7HxJD7uf6N6H6pJ2bU3rWbYAb/KZWsox5Q3LB8gEYLDA6l0IeeNbKnBhLLpz1BGu6DnzgD+/+
  template:
    metadata:
      creationTimestamp: null
      name: ismatthealthy-r2
      namespace: ismatthealthy
