apiVersion: apps/v1
kind: Deployment
metadata:
  name: ismatthealthy-web
  namespace: {{ .Values.namespace }}
  labels:
    app: ismatthealthy-web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ismatthealthy-web
  template:
    metadata:
      labels:
        app: ismatthealthy-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
          resources: {{- toYaml .Values.resources | nindent 12 }}
