apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 11Ti
  volumeName: plex-pv
  storageClassName: "nas"