apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sauna
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thatsimonsguy/homelab-k8s.git
    targetRevision: main
    path: apps/sauna
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sauna
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
