apiVersion: v2
name: keycloak
description: Keycloak identity and access management for homelab
type: application
version: 0.1.0
appVersion: "26.3.3"

dependencies:
  - name: keycloak
    version: 25.2.0
    repository: https://charts.bitnami.com/bitnami
