keycloak:
  auth:
    adminUser: admin
    existingSecret: keycloak-secret
    passwordSecretKey: admin-password

  production: false
  proxy: edge

  postgresql:
    enabled: false

  externalDatabase:
    host: "192.168.2.20"
    port: 5432
    database: keycloak
    existingSecret: keycloak-secret
    existingSecretUserKey: db-user
    existingSecretPasswordKey: db-password

  service:
    type: ClusterIP
    ports:
      http: 80
