image:
  repository: quay.io/keycloak/keycloak
  tag: "26.3.3"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

db:
  host: "192.168.2.20"
  port: "5432"
  name: keycloak
  existingSecret: keycloak-secret
  userKey: db-user
  passwordKey: db-password

admin:
  existingSecret: keycloak-secret
  userLiteral: admin
  passwordKey: admin-password

hostname:
  host: "keycloak.int.matthewpsimons.com"
