replicaCount: 1

image:
  repository: traefik
  tag: 2.11.6
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingressRoute:
  enabled: true
  host: matthewpsimons.com
  service:
    name: hello-world
    port: 80
