apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingestion-gateway.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "ingestion-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
