apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qdrant.fullname" . }}
  labels:
    app: {{ include "qdrant.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "qdrant.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "qdrant.name" . }}
    spec:
      containers:
        - name: qdrant
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: qdrant-storage
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-storage-pvc