apiVersion: v1
kind: Service
metadata:
  name: {{ include "qdrant.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6333
  selector:
    app: {{ include "qdrant.name" . }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}