replicaCount: 1

image:
  appName: hello-world
  repository: nginxdemos/hello
  pullPolicy: IfNotPresent
  tag: latest
  containerPort: 80

service:
  type: NodePort
  port: 80
  namespace: default
  nodeport: 30001

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
