replicaCount: 1

image:
  appName: hello-world
  repository: nginxdemos/hello
  pullPolicy: IfNotPresent
  tag: latest
  containerPort: 80

service:
  type: ClusterIP
  port: 80
  namespace: default

ingress:
  class: nginx
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: matthewpsimons.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
