replicaCount: 1

nameOverride: "hw"
fullnameOverride: "helloworld"

image:
  repository: gcr.io/google-samples/node-hello
  pullPolicy: IfNotPresent
  tag: "1.0"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: matthewpsimons.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
