replicaCount: 1

image:
  appName: hello-world
  repository: nginxdemos/hello
  pullPolicy: IfNotPresent
  tag: latest
  containerPort: 80

service:
  type: ClusterIP
  port: 80
  namespace: default

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
