apiVersion: v1
kind: Secret
metadata:
  name: nginx-ingress-serviceaccount-secret
  namespace: ingress-nginx
  annotations:
    kubernetes.io/service-account.name: "nginx-ingress-serviceaccount"
type: kubernetes.io/service-account-token
