apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.sealedSecrets.mapbox.name }}
  namespace: sitemark
spec:
  encryptedData:
    token: AgDW97vgyuNTav7/ePXfqqlOOo6pNEIxzKfKoN6KSrQXC63vQ+1bC3s0qChr6nC9DxCgtBqnqgxW9r/SqLkAnvC1pNjr5QRFkXrk3hRfwav4Y5pTvN8Kg9hxTDYPp45XYgHc7Z/9FhTTzMahPzLLpQ/HwNjPntOtfOL4j+s51TihHYX7qQfIIQbXxsWqWicg4H78wI5nAdPDs2mDscsX4D/o+vckBgs7l+yf2wQN/a5EuQCU9QsirLpmDtqb2Felwb7b219isLEhDbYVwH/XG7LvkpauaKoxNol138Fhtp1i6gnn5E3k5QHcNF4yUJA6Gb63137PI6FP3xuehQ08bTRXGO15klL7SDSkWZD5isz952ZL6fHAgShlwUIbz5GPqb3opNjrnJiBoqbCxdy64ZcqOObBZo7y4t6PkQ5jMuK9DZn2OzYlajnngwYwMXdkRS0j03wWhJBNTEgn/IzeWO5qMq9BO9XW/b4I6StpjgcLuzTLfE41W40Q0NL3tpZW6yjlmvx7cW24sdREreM2Fa/QC8mYwHEyKc+Pm8P4PBlcUq3pxe2jD7PJXmgf6zzwrPo661ePAFB608l609gH6MxmCWDn8Oxzs1/Wdy3THPnbG1eUG8ybei0dowiDwdYsnhq/PYDX/krp3cvAzulNHwTb935X/7xPdbEJBvW8nPsTNzWJjkeUVplKTFdzgnKJVvCZ/VgIeW5l3QsUUukaho6bg84Er6Yj9b6IuGWxjWUF+lC3VrWEr20OU9KTnzdmCQB0LPxHAJ3ROjfep0hS2yX2dU7YhEceT1MJf/5hQtR6onv390F4nIq4YevRCv0BGd/C
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.sealedSecrets.mapbox.name }}
      namespace: sitemark