replicaCount: 1

image:
  repository: haugene/transmission-openvpn
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9091

persistence:
  enabled: true
  path: /mnt/nas/data
  mountPath: /data

resources: {}

openvpn:
  provider: PIA
  config: netherlands
  localNetwork: "192.168.1.0/24,192.168.2.0/24"
  puid: 1000
  pgid: 1000

sealedSecret:
  usernameSecretName: openvpn-username
  passwordSecretName: openvpn-password
