apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-webpassword
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    webpassword: AgA3/V921/UmXqHKztURWIkzKkCbV5Ok9y0uevWCCN4Gcz9VL91H7xll/KEUQBl142lF80HiMDuiQ4x3jsM6LdiRelRdZfA1DDhJf4+HZFfH/DYxBnK+8Pc1yA1ZQfiKi8nj/1kpcC/Y817WUz4c/ASwByFS4Iu1iNKrr8x1Fci/YoSMgGk3u4hF7Ms3wBeIPoHRkudPKm2pwHru5Uw82F+UaeyL/+Ithk40tTnAB5Jx8XctEe7SZiivnI8O+WW2E+azZsE39dIChpuXCunC4klkx3fxroCVPybyfL40NeDG1Dfh6CBpP4BEraz/VazQvZkN4+MDIg2VDMXWEMJVeujPW6wWiiWY+3ux5o0L4yRNwrEKdS/3Ig1be750R3CIsJLgK22JIW3evD5GkPAbtVqmdyulQTvjJSkvwyN9hlQt/1xzt77p3DRwFsmBnBEu+L4U3cOpw7FNn5cqFWlg0qIdMt+ZbQPU12LeiiaoGsWctuZb2ZP02PV670rrffGe66ykWMfmme8+CQ0gPWKPE3az/Sbw9WjueYpbBDv8vmVB5YrcMZh/gFxmga5Ox+EaSQK94dYJ1EEZkGo8amjLRyNKZMGbOIZpvQmXSzYSsrTMIUpVZhoz/D7jILKNxEyTMKk4VQK/NN4ct+ha+MMDLnovspSkZQ7NEUApZlUxCdsUvYfTM39NVQ/nO1WRZRwUT0GCzC4ljJ6pIzU7FiNTRg==
  template:
    metadata:
      name: pihole-webpassword
      namespace: default
