apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 53
      targetPort: dns
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: dns
      protocol: TCP
      name: dns-tcp
  selector:
    app: {{ include "pihole.name" . }}
