apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: dns-tcp
      port: {{ .Values.service.ports.dnsTcp.port }}
      targetPort: {{ .Values.service.ports.dnsTcp.targetPort }}
      protocol: TCP
    - name: dns-udp
      port: {{ .Values.service.ports.dnsUdp.port }}
      targetPort: {{ .Values.service.ports.dnsUdp.targetPort }}
      protocol: UDP
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: TCP
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
