apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traceroute-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thatsimonsguy/homelab-k8s.git
    targetRevision: main
    path: apps/traceroute-site
    helm:
      releaseName: traceroute-site
  destination:
    server: https://kubernetes.default.svc
    namespace: traceroute-site
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
