apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "openvpn.fullname" . }}-secrets
  namespace: default
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBTgSR2fSXvxVO3gdvFMs+scVYLpPgQunmWBLWrR9f/n4sPGIDlZdO6iSe3ih89MMU+091PCV8mCPm7MQm7F805TWUN+8CpGHO+46l6bfqz1XeLjTL5qoYVA+mKLJFfL+BP4Lk4aMgypMTiEL3Dtds37KrHZidaC1KyzNyF6f3PQvNqMioZ9rEn4MXdzVoOHhJBP6az2RCh8LEChfUF76MnLu/wMUjeJJK7S/iDnukJ/VoTfLOf80mIfKAEFIuX8vzSeDO+QjgARjWtS8uQRAJ8tivF7DOo4LO8cUBZiespA8tdaz4v+creipfzJBkrn+LSYsKKr/wX7Pf0bjpvct3zT/58GVfUJznWd97kCO3weS5y0pbRTz01MIDzukhJJrjW3Wgfq+IiYU7EiK+JfInJ6qxuxLrkrCMzts1z9uU2WPDc0puF3p3rSXXPV3oKSuJDqIO6/jfRIaSPmKPi7K0+U0dPmt/GLncp7Oz9Ke4yNn6DBdVA6HRZaQb/BFb+fyIIZ07fymXK4bLJSuubatjCImDL0SRr4nJvSgCp/i+Gw9HNWAxPRn/uxqIy49bxWdNC08ZS1e60Q7YoSng4ef2srgh91lL7oO0PkcANDUaUqutue+QosPs0t8hH6ICVPDOX5Qf5ZEzxnS6D08l9+6Hbxvw9Y2faxG6IXbKBYekmPZvry9YTe+3ndP/P2LbtkrhKWJV4h90FWMzuJWqfI0Pfu5JdbN/E3MqJnPVjx3A3qXvzrvCw3/ZcrHOg+w==
  template:
    metadata:
      name: {{ include "openvpn.fullname" . }}-secrets
      namespace: default
      labels:
        {{- include "openvpn.labels" . | nindent 8 }}