{{- if .Values.serviceAdmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvpn.fullname" . }}-admin
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceAdmin.type }}
  ports:
    - name: admin-ui
      port: {{ .Values.serviceAdmin.port }}
      targetPort: 943
      protocol: TCP
  selector:
    {{- include "openvpn.selectorLabels" . | nindent 4 }}
{{- end }}