apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvpn.fullname" . }}
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - name: openvpn
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "openvpn.selectorLabels" . | nindent 4 }}