apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - secrets
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources:
  - ingresses
  - ingresses/status
  verbs: ["get", "list", "watch"]
- apiGroups: ["traefik.containo.us"]
  resources:
  - middlewares
  - ingressroutes
  - ingressroutetcps
  - ingressrouteudps
  - traefikservices
  - tlsoptions
  verbs: ["get", "list", "watch"]
