apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
    name: web
  selector:
    app: {{ include "traefik-chart.name" . }}
