apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
    name: web
  selector:
    app: traefik
