apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chroma-service.fullname" . }}
  labels:
    {{- include "chroma-service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chroma-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: chroma-service
        app.kubernetes.io/name: {{ include "chroma-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: chroma-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: CHROMA_DB_IMPL_THREADS
              value: {{ .Values.chroma.threads }}
