apiVersion: v1
kind: PersistentVolume
metadata:
  name: gotify-data
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gotify-local
  local:
    path: {{ .Values.storage.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [{{ .Values.storage.node | quote }}]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-data
  namespace: gotify
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gotify-local
  volumeName: gotify-data
  resources:
    requests:
      storage: {{ .Values.storage.size }}
