{{- if .Values.publication.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traceroute-aws-journal-writer
  namespace: traceroute
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBYHafYav9EjeSLM20oAcj+MCF1LrHdnYFDEnDnaj3qRyLbqfvZdY4ZrNTTh5PrqaE0BJgnpAOafJcVG7qtmTP5dW16Dr/2NT12brhxeOiEUDeMbU4wNbsSbUBPni8dpljuPyjfOM7G2Aeo48ECUrPMIltkotDeVkxrP5QSF0abwnXdnPDvyM8JbQR9YjodItkzkn3MUgJrlveK2WcA81LcqjSu5LDlmr0wcMhvecL5iWhF1CIbPpSAIr23AbTI5l8THupjpsfRv2F1hxtIkDfT3FtorVLJh6GlgLM/hYjIgvMSwZk2DOE7ggMcN25MtpOl12UfRp+1/ZemnHn0yPsop3OPOS+LD/tYfeDoRLSnnrzx2mZdbQcaub3G1trds/MQYUTBqA4r4NHuaWau0wepRH8VLh1eZvhXoapMTLDXLUJV1sYPvHZj4KmIiyPTIT9LONALjUkGbKlAGdkD9FrvxaplfHupV9m+FU26b7dHAnsDUgJxmxdFX5YwTu6TPfX40ZDQ/LLSNbCiGLCElWZy/viztODeS7NqzTTXAUqO/iqzSpwuMXxKI6vft1A6HyuKsgey4D/ybc6cRP4ojEcuihnBlXJYUNDxwayuxPQpyjuxlimaF4oZlWoGnSgOjr0OhoZq5PzmtCVZkoZDMFe+wscBoInwQc1drLbguLBPlE9gWKUdcOgrEGTy/Lz4gd35u87q6ktpj37Ot5Qs61+fsGgP/A==
    AWS_REGION: AgAEhxcq1YC+wTQ2A9Ap/1LHZlKZ2oGJ/u5h4CvK/FABvOfRwxV880bKt+awZywMMqfS4OuLnaotaT+tODh3hRlWDqr2wwG3lE/k0GsZP7S4T2qmVZH9qFpiTWEJnB3lGZ4dFAmx+C1ji25qh8jQyquoQvkyFSXQ2X97t32s6baacHg6IuIKRzKZX0LOQUioWXTMZ7iSYrjIvhAlNFF4kNekJfwGsAUHAG6hP0uosEbIZOez3DfJn/GZW+ytPLCLiehauQjVkayBc7jocRyyCQJu/SU2phHxyb7xBZkwfXx/VM1TMdnMp14LT2r6YFJRVM17TrL/7Q0MX6TOwumOIrFHz2fb/2+RixjwKWa8VRFxGVKsQBLcJbli9kC7hzvmNtD19AyiL1puZSW0sjBDJldcAAq346q4YwmhJb9HEec2TAgDaCTWEEo79FS+Ze/JAG1vc2X2TPTWXYC5Z2Fk5DtN4HMPdzNagnJMocmi9uDGMw1Ehql6OFGCyotJ59GIT8w2FVSXnrab3zKFQeBl4zzq1UrSh6EIzbidePbTNytoOY3eEYzHB+PhJRSw8BJoLVBpAIvro11BhCY5Q1d+oo57vId6ozGEOcCwg7cgByPF5Ncc7jnDREMayAesWJurkTmDF0ztROGy8/WcAWwgsHEY0Ibp604YopTR3tKBziVlN3nMVaKcNd6wzZLBwOZgUDjNvzOumw17zSg=
    AWS_SECRET_ACCESS_KEY: AgCK8kg68siMa6i5OIxdtQrIvABShxWXAjKTk1ynScqh5EO3PrOMfqpnWrO9DIFHc08RTBGOawKEoed0kB5ReWhR+n6M6qFCof9G9AuH/A+XE1fcpgU/K5A3NURC5pjOtZ/W8lRsBvYrjT0mL3CCPB9GdkpXyV2iN3e+VybRILyFnyl1QQ6NPSx2Etq57IqFLhq0zpF4obhbfh+PZdHZqaSR4tolaN/thQAPn967zeiJSlepOFsNSQ5Q6oOa0B1aJMeA32jntBQecdgwAuW7VoQZezI5ImZNp7zs6d2hdqcmhj34w4M5tK0mR+4Xl/Z5ouzJhrqtayjPuPs7+ZnOrw9/K2psRK354Not4wZQ2f6rF/vZ61UaEBw2j7Ei8M/4ELd2dKvX6VHuU96FSiAgPf2BsvQUKMYuWvfKatXiGiDWVgP9m3sqQB5MhMOIs5xjKNXW95r+bhn8txoDbD+Og89XSwPO2ngU0GFLzjml/x+WdKmgL4H653o/NnLFoJUkohLIEOfRYl9n3dOvSNF9gbApGkzVUJhJxRtmz2+aT+ZDpGkdZpPKhex9I6Bt514sL/6/lKzz+dKtJe6MlT06v9R61diBIL3TtT2CcsQ5xj+0E0myI2S5c1RZdShPetniBr1lDuXWVz2NMbUOXUp/8j6430nrorDSAvTNP/JAtgFtcCVUNWLTrAymcYlx9JoHdUld7wmSFwwynnp66J2B0GxOctSYNK413aZlpNH48mGFXqeGFNIxOElT
  template:
    metadata:
      annotations:
        traceroutehealth.com/iam-user: traceroute-trial-journal-writer
        traceroutehealth.com/rotation-due: "2026-12-10"
      creationTimestamp: null
      name: traceroute-aws-journal-writer
      namespace: traceroute
    type: Opaque

{{- end }}
