replicaCount: 1

image:
  repository: 192.168.2.17:5000/sitemark-frontend
  tag: 0.1.14
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  class: traefik
  host: brightbadgertech.com
  path: /sitemark
  pathType: Prefix

# No environment configuration needed - values are baked into build

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}