replicaCount: 1

image:
  repository: 192.168.2.17:5000/llm-orchestrator
  tag: v0.1.5
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

ingress:
  class: traefik
  host: matthewpsimons.com
  path: /api/v1/chat
  pathType: Prefix

env:
  port: "8080"
  embeddingURL: http://embedding-service.llm.svc.cluster.local
  qdrantURL: http://qdrant.llm.svc.cluster.local:6333
  qdrantCollection: matt-chunks
  mistralURL: http://ollama.llm.svc.cluster.local:11434
  mistralModel: mistral
  mistralStream: "true"
  useOpenAI: "true"
  openAIModel: gpt-4o

sealedSecret:
  name: openai-secret
  key: api_key