replicaCount: 1

image:
  repository: 192.168.2.17:5000/llm-orchestrator
  tag: v0.1.3
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

ingress:
  class: traefik
  host: matthewpsimons.com
  path: /api/v1/chat
  pathType: Prefix