apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jackett.fullname" . }}
  namespace: jackett
  labels:
    {{- include "jackett.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jackett.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jackett.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: jackett
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9117
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: {{ .Values.persistence.config.dataPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "jackett.fullname" . }}-config