replicaCount: 1
image:
  repository: 192.168.2.17:5000/staycation
  tag: "latest"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: matthewpsimons.com
      paths:
        - path: /staycation
          pathType: Prefix
  tls: []
