replicaCount: 1
image:
  repository: matthewpsimons/staycation
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.17
  port: 80
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: matthewpsimons.com
      paths:
        - path: /staycation
          pathType: Prefix
  tls: []
