apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-webpassword
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    webpassword: AgCdl/TruhBNownkvi7Zpv/R/YMFSNkCcVTONaPbcq9Brscd5bGfFGG0fJWQB0jkryGhro//kHRjTVJmxv478fZdZk83/F0wVlLwxSxsJidrJaduecMjKnOPiHtTmUaD793bq6Tysi8mC2jukjoMGcwGi/NGdCcYBCE50+MQknY6CUJDYexYdqQE/5K/c7p/hh/CasQuMmfvKP8Oas7weNtWrbSjtCV1ecPqZg2/0wa6snASk35MiIiDimJuvIqNXoLFq22ZzrUkC5FJBYgTbIaYebupnAMeJ5fBdLpmzYHrjTwgVOCoyYp1zjtGxIJQEg26mKCYcXFVjBeWd5TprMMOk7jnACa6+6w4Cic8buwH7gwXwQF67V6xPsqY/X2sERle+MOUwsGYVsT/4/bmBBfoaEkn+QcEDEoycJ7FKbWiPJzg9dUyi4jk0wRX1gEvAI81FEIlrZQf9Jahs0CI2Q+RYpAtfKX7dYEGPDPEVcYhflawoz+wgN1YiG32VZZ6DIRXRPAszZ7nJffAAW2f4a+TfGSieKFBl3J03dJWhHOV1DRwcW7eurnI9yCpekBr7dU72lmP1Dob4YrFsABsQ0tP4eouKbOxsFvoLghmv4Heg/CWMJvjbhqyd2q5Qau+6Oc04IKrbgbOz5r0RdqYrZiH2Rnjf0EfGBFgxLwrTj6970kG1D1rqVzF5mVfEqdR8KvgPhHDxvdHelZdhpF9gdSV
  template:
    metadata:
      name: pihole-webpassword
      namespace: default
