replicaCount: 1

image:
  repository: pihole/pihole
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 53  # Example node port, adjust as needed
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 53  # Example node port, adjust as needed
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 80  # Example node port, adjust as needed

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  dataPath: /data

timezone: "America/Chicago"

sealedSecret:
  enabled: true
  name: pihole-webpassword
  key: webpassword
