replicaCount: 1

image:
  repository: pihole/pihole
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    dnsTcp:
      port: 53
      targetPort: 53
    dnsUdp:
      port: 53
      targetPort: 53
    http:
      port: 80
      targetPort: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  dataPath: /data

timezone: "America/Chicago"

sealedSecret:
  enabled: true
  name: pihole-webpassword
  key: webpassword

hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
