apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.appName }}
    spec:
      containers:
      - name: {{ .Values.image.appName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.image.containerPort }}
