apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.appName }}
  namespace: {{ .Values.service.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.image.appName }}
