---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traceroute-google-idp
  namespace: keycloak
spec:
  encryptedData:
    google-client-id: AgAgOp9hxgFS3kIhv+aiJaFhgygJkB30cCAIuP/ufbp6BeEM5kgmLxuL688FT2D96x2iZ/drHtZG5aHahsxb3jM5yDra/KqUpYn3hOg66ZDzh1iWrZSeR4oJdYwBiW4E25ce+SPpxS0uOCEqEnxYu9F/7yUYf5Hb6WF3KLB6Rs+AN4qa7fzDaS1bQmiTbsBSdS/51HIaLU/lDwZ8rN0gxt/Ev6tojOKlLE132RBnrOFtteWQGigarRm9baJS63Ekl2ctcEmPKo51uHb+uejl2IKVl7hYW5PVPOGM8HVQL9CjCSD7Ht8dnNcxSKlEhvSo+scWbl81Y2pT7/5C1voQOe5JYS3M7eqryvYPAc2btsiDXhZsR/mCqJ1J/3KuC3wlC0Tl4n22NAdvihJgPAxwJbFbuznbywFzfHWkcoADUDpk4UXDrrdPOKH20VpYXj3QYiudITZ4iFJLFGIHkAPShyPfyQHalewUYFztrecljVUaZUIKCPbMeV2i24HQICZlSEW3pEjEt+066K5aaTblUG/UxHFM04owtsVktVkobMtUFa3vpDulDxiGVEq//ZgjT/RyQbMFKbu/A2r28q9qY9l7SAjvmRPNQzvAj1fzG8qZA/zRWJrp0my48myOmbT1ubX8ZY5RIh+GdjiaFGKdqDZtT1HGw0N/JAddYBEYg2iiY0zby6RD6Flec+deS9DrRdx1qIMDZz5ybwuy9bK+BthoXZtVsJwbkRpsQWKMe02KdRUFGd1BhtWbGHXwBDRvWphAAfAEY+DpP48UNgndtAY4ly9EOc4HmN4=
    google-client-secret: AgChKG6a9KUXqIFSwOWffVQKdl7/KDyt+kCLZadbjPhKqC+/sfnpDxtFk7DHtCSaw+VtnvLEP5jd9mM2umj/Y9I4eUfJnKbQQYTHVFd1kxbV0ww3/XjZxaGejXlqKFLkGgkpnMSachHEhcShOOd+yZ1yedMZIS7jHUVG0kIdctyO7vYEZ5O1QqvfEZmrGx+JkmqXv5zmRLcuddjlo4HWZacI152wjipNOPtTe5znnkSSoci+wyyBaTELCbOp0AHkOePleQFoAEUQGIh+uR/34s8smpF2J/tZgCLgpSrfzeZTHrS7DwAbXIH2VUpFk/Ozbl8VlamrlH2VQLs8Ycxtbrc2MPOA9e3PueTekWg5IQMfdmNSifSvlze0QOJa3nacgbGUpELdup8G6f2msvuIhwuagQ6RcGKvbe9PV1hMV/opv0yy27LLB2yu2RRKBxyAsDos4RvTfYXPyp0vdcv4zE0e47VImNhp7wGbowi0i4bNS+RIL0zQNeqqgl2lQ3ac44g8hN50uj+mOPttlwrx5TnE8IwKm/drmsbhsahJTSOMjYQyDCs3Lzi1aM79ba3Y3/0PH3ty1rZ3FuBBGGrclyQpFo4FElhYCj46QOmMelSdtHT329vFVy5lJUC+Oxec0ecr+97Axgd5YIMRGIYo9+IYetcgaw0RihRQzqd/yTBUWw8v2D2ntFpUHEpgQ+gnDEyuGzIVjzd5pgSSiUMOdgY6cefXxJ/NCqjx0gwCzWjmwN8Cgg==
  template:
    metadata:
      creationTimestamp: null
      name: traceroute-google-idp
      namespace: keycloak
    type: Opaque
