apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: postgresql
spec:
  encryptedData:
    password: AgCIB92Ue16U0OpCKnUageU71XbBmCH0UVsSa3DjCqwvro/Cl4xNvXNBeInOneethwvkxZKEOH96dHUjlSx3af6Q1oMgLdoY8/ft2haF86vJ+pqKDqTrHDWP3sEuS+85dEDOat/KzkjrGf9bnEMbwOMrkSA25/dQVTUD0PzViSuJIWAAADkw4OWguIQOcxjOY5Cgd/jW+iVaBvfSItUIEQHUDy3qk0MkNIBii2qH31ETwSKJVSZjKp1gRzJVCDgjwLffl6x5ClBtTxAT9HD9K3narD0aeHsFeRoTBhft3bJYgHleFhij4gzDXU0YbYiOJX24vI5M5RB8V9cBKJkELF7kp6JKc16HhyO7+rvpniRm+9Q9bXm05BqgXQACD5Ot+bWI2kAqqghYXwClkqDNnrLSvqlwhHuzfXYArBeMlfz2oClrpwIrZ3L8hzoJCviiyfWnl9HSffHDi/rx+OxqD+bHSzIS9xy/ERQ6mJDRU45hV5kqmgecRSRO3OKdQ+FVKlfhT+efF+B7VANjOh+42SzInc6/Gr50e9rTMjYqObKhvwHthyHLA/6hb4N0BIi35iQ02ODQk/LgW4XGRouxTC+CmlyWdvZyDDnti/JyEjqcp7o9exfv22gSkQdg8cG6KaNlwZ2HIVIb40dXiYbVlgwifaSNginbwqdsDzE/XpuHiFFHaLZSl0R0Ar23zpyDLfBHiC+DIzqdDRWJN6U=
    postgres-password: AgB2kMRMeWid1m10tyoROrhSd8GkWnnQT1s/rDHVN3DcFs/1PwrKGhX7hG4wHoR9SSQDFjcQi3HsHBLRA/ThoNYOdG9i+TgSVLab+p0yVilujAZ/nOE1x2TokOC9TwzU08jtdtHMa29H+MKNGDKADBLxkFbFSJ5gYfdAufSXuYSf8bVWlNr1m+R5Z7ZEkZPoU0yvEsoc/C8T7S0mOMWX57pXCfJqjpJkNwIieEd6vfW4FZJoQCK2vGwvAZPS9D3R6+7LatS0MAn89f+DHO6dVz7lS3zq+epNkCVlwMYUqStsDlq51YkUHz7/lVt22d7RAWYU5y/RWSH+i++KgkH34yCEEDTYwCL1EaWs5VnTDaPZ4bGXlRc9nxMnglFjRJHtj7MQsK4MxqDwosgTPFin70WJfksyptAiNuyR1DCs2CXGXD9XI8ye0hH/wP39YXZEVy/qcUxQMzke3hp1y8c+8pJQvTiD3s9Zim7ACsQZrYoqfG/F8+C16KOQQIdPXupPsbrvPw+M1ivkqk/18rUC/h0B5vodY2G5QFVor14mru3w9Wuhgyc8bPXH/FxOuSEArk5p1yBEGJHKUZdcF+m5wpBXdwB7yf6U+fzsreNx0rMvWJFxI5JCWF3aUoI1u9Y5fPXtvBsUwVhfw5JP2432X81xoGh1WnNZAVNERFgnfnjIdgSAFDLZ47Vuq3yl5abQ9ikg3rm4wfMb99saTA==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: postgresql