apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailform.fullname" . }}
  labels:
    {{- include "mailform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mailform.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mailform.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mailform
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
            - name: TARGETS_DIR
              value: "/app/targets"
            - name: PROXY
              value: "true"  # running behind Traefik
          volumeMounts:
            - name: targets
              mountPath: /app/targets
              readOnly: true
      volumes:
        - name: targets
          secret:
            secretName: {{ .Values.existingTargetsSecret | quote }}