image:
  tag: "16.2.0-debian-11-r0"  # Latest as of now from Bitnami

postgresql:
  auth:
    existingSecret: postgresql-secret
    database: "mydatabase"
    username: "myuser"
  primary:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.2.20
