image:
  tag: "16.2.0-debian-11-r0"  # Latest as of now from Bitnami

postgresql:
  auth:
    existingSecret: postgresql-secret
    database: "mydatabase"
    username: "myuser"
    forcePassword: true
  primary:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.2.20
    extendedConfiguration: |
      shared_preload_libraries = 'pg_stat_statements'
      pg_stat_statements.max = 10000
      pg_stat_statements.track = all
