apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq
spec:
  template:
    metadata:
      name: rabbitmq-secret
      namespace: rabbitmq
    type: Opaque
  encryptedData:
    rabbitmq-password: REPLACE_WITH_SEALED_PASSWORD
    rabbitmq-erlang-cookie: REPLACE_WITH_SEALED_ERLANG_COOKIE