apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: rabbitmq
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgArFkZwpUfGgI/6//RBguMXDLqGE+Npghxmp6qLozx8P6Pqk8XpUWwEnxfcWTGgs+praisJfTRaCl6adZvgFTpcjXmsAs/giNJijGRsCtQrh6x0gkswSM0sBBW80jBmMsf5tsWjTsOxvMUwMPodFULg4Erjzi3u+AFgYpeqIvr4C52ewvSbzPWZ45K0jrCEp+lw3/ehXsnwTyYnLGwFphoSmVmLEpgykgF1HRKPDNR2+bEjSZa8JO91FQRmlCUb8OLmXenyXQvpALQE0JVAuaoaeyzxNfrAucaE+md6pC4aKJfaiDnN2SMt0qZeb986+NUlX7UZQZ8xnXeBXhLGVhIKjxjyD8Q5+PNB8KMLoXTkBp1y5r6MrJObB2bquoqphbsj+4RexHp3m7999pW2BvYCzZ16HgyfDue6J7TFJi9EyVILq3sMbNlHMQU4LKvmztc0mxg+j2JNc5FoyZRhNbOPO/DdQKsiu2Ep6vD4PujH03WS+yFr/GkYGmgHg3dibzqu8UIUw+3mzZkYnMbbRPfRkiQ02HZe17zalGgMHSeB1UVy0dHokBRLjHl1VcqzLlU63/zPOft4HBXYR0v6XhdJjnwBFDRJd47VZciguPIpkMW/AX0GPtxT4+8u0znfvRLeeAoIzW5Y8f1uk2s1g0g+pD2oVssuCOtX3sbVWpgshbmcvyhf0NJn0dL7BRVszsdzW79Z/pytrRbA8B1UjEEZZTTGpfNNeF/lZ38cIyl8QA==
    rabbitmq-password: AgCwgHwxCLcdMdH6CKEeoKRrR0a4y1wHSaXjW5mLyaT8jBnvo+/w30h7/vdpcgxAEsZEIzW1qeuUdKTlygH0cuhEs319zrYSJqSZP3qfkWg1/M3eJv36cOh+gEXmnpIIJ0i1n0rwI4MvlVi1SAkgZXz2owUA+cSoy8SPDQWQMkLpGh/KbE5PPMeV7MJ77vDtHa8icUyL3LuD21Yv0m0kLkdfQb4gz/4C7gcfg9nzUUEQOitgh+0Z7m4AnwaoJzzzNLmyWa2+DaOM2N2ORybT2FjEs9ONYKjjvw0yIF0RghUiXY1NCMzMD9XKA7btRCkmMO16Ud2/1KOUAgi1PSIjTJiLXA/mh69KP4GqUh7kg2KyUQgLE/LajaPeeanIKtxdVGkP0IhCkMBfQ9ad+pc9VdJPrFkOK30eQhAOMYAXRTqzVWTE43i5z2OSZcXX/05E9S+0/5Oabyn8LAUthuPuFwa6WyOKewYlz4C0stogZsdku5WjdD6MNKRJNSAH6kuot88GGfF8COjd1kwn6y7lRjVlV3Nmvhxx9wrvKX+mOOcNRC3TCuDyyFqS/X3+qOqEN2OE/hAgUQ4/OrdAnG2xvjym6y8ByLmv2j4J5c2tBrkbVY+T7EWcg98YBM8T32A7fXWU/+VjFbgIftU79jJE0wTnZNi0uouDbL9+/FsEycaSyPG/4a/UUEOrQB6ND/bYQ4kW0VBVCkH+wXfPLKJvV9IA6QPDGQE3G/pqm5TlsUYJeteZt3MItJQNiSOfKg==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: rabbitmq
    type: Opaque
