apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: claude-credentials
  namespace: default
spec:
  encryptedData:
    .credentials.json: AgBeoofuv7vSubunNZR+tDHi0ajETWjrRtHIz+xsXWHr/aT81ENipZQz4F5TbKRq3yJUX4fQoA+LdkzPfz9UE112v5eGncFnQj6CFWTUsDSTKHUcbs7X8SlwjOgAzTt7A5XoNpdZTByS+3Y3JxEN4D4IKb4LGkSECkkwFJfU7HjIOzNMQjVL/KFw+UMlp8zZWmJAiootlfrmD6azTcQzDAJFzYaLI+QWflONRdpEUhdlgoYkOegM2J3Gx2oBHs0yewkXs+5PJruNaYfs7b52jVmjtMP45Gpp3CHAf8+TRWZ5K/sDffZeekWWTbRWYcAOMfwG51Zz+Lk2IF0tTTUgTUK+/2A2QLyogYpNrRSGR31WPI9ga/NjYTRXPtufxXxONNF5TK4L4Ook1eJCIoD5u4xB2TixSFmA2VCi7+oeqW5zzWgWN+T4Z5HYEgO9z3OyrkwcjC/kIYnnWv8sxgRKeOFsNM+byd1e0eh2ohiEdJqorrjvhbz+MvMGUVXPQp85t0u2rfuppsI8pzq6JA1HhaBEAOEMWhEIGd+6FB5e1oAbHdoSycOwrDn+1z8qtPfZmSwP2fFvBUMsrU6irU8kxZtOTVXfUT7bBb3XRO+Ry06YLDRdGTwkPcOZF7N6ShU4pMvoqNGc48/EvXTVrTgOkkgG5eLJudqojxDKNLgJk1TkDou2tOYrv1T3ionhMiEet5EphNaOfSWvZ/xwrDkOka3abvnQz+o5yt5OsMDMCl/NXoH0ZPJYI6djBz+jbAFPOvoyEtRrxwwj/gVx+fKwPMN01cCmeELY/fpHeI5bE+zRWCRVxFBLrXwpxNKT3GsCWXv9zFdJ8LyIMPWjCYDFnvIWuIjVne5EJkspI+76X83X6limPdsd2eZesJa2/jcdHTWsvEwva+a1iP8TKiM0FTBYm8yYX4nk49EF8N30Tfqt3HnWEtA1aMr+wjfhQHYu5Y+PZ4J97AQFVicX2UKet3I+O+Jgx5S6uTtv8FWcNJJFco9n6cf+JMYgfDwz/y13/7usPKtCPmLwP+DQ06U20UFDwuC7xn2ZIlfUYB6AVYR7SG7Xpkb9LkOHspNtA0TSU/2ZXokt/Z49xxDHrYIw1YhaiKouMxtxWYVIgxqy4yeB2ov+E/6EH1Wco38EgVgJ4PEkms9twV3YhVgB6hb/S39iRz8hk+fze07NsM6W
  template:
    metadata:
      creationTimestamp: null
      name: claude-credentials
      namespace: default
