apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-orchestrator.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "llm-orchestrator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "llm-orchestrator.name" . }}
    spec:
      containers:
        - name: llm-orchestrator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.env.port }}
            - name: EMBED_SERVICE_URL
              value: {{ .Values.env.embeddingURL }}
            - name: QDRANT_URL
              value: {{ .Values.env.qdrantURL }}
            - name: QDRANT_COLLECTION
              value: {{ .Values.env.qdrantCollection }}
            - name: MISTRAL_SERVICE_URL
              value: {{ .Values.env.mistralURL }}
            - name: MISTRAL_MODEL
              value: {{ .Values.env.mistralModel }}
            - name: MISTRAL_STREAM
              value: {{ .Values.env.mistralStream }}
            - name: USE_OPENAI
              value: {{ .Values.env.useOpenAI }}
            - name : OPENAI_MODEL
              value: {{ .Values.env.openAIModel }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sealedSecret.name }}
                  key: {{ .Values.sealedSecret.key }}

          ports:
            - containerPort: 8080
          resources: {{- toYaml .Values.resources | nindent 12 }}
