apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-secret
  namespace: llm
spec:
  encryptedData:
    api_key: AgAe2wHkc1HGtF1d3cvLoRMrYq3gSjEbXqFhc23SQl5fHEvAXfjUZ++NBS/JPrRL+4MAehlnM0eU+5Zi7F11XJHBu1SuNTd2F+5RI3/K1cO4sbi0FRVqyPNRd6jtytTujQ7iUhtU72dUvwtgavnqIGmbG7/qLjTYJzSRvP0AmChFtVTCh4BpAAMwTG7TyZ1j1b4T5Bz6ue+/KdYSw+hwMK9+L3C/L7HRc0s4SkorSSgPS9lT+Dpr/2n9602qEAkey8fbX53LQOxWV7e7wOl31Gr6ROtgsiltpMGXrdWsP8T5hOdpqF4Kqo++0cBlm6yc18OTNnMkcHfLVPCaS44xXcMqrbnqg1lyeY/iYqwFStYLkwBEg5src0KmK13UmLL3H61wzir3I7JG8USRS7j5+GJtAdSU74Zkdma/F2A2JkHMomVytqO8p91tsFn7lVZN2PX8G0mh2d0170v1QPLSwOwy5cDIMMcF1kw8ftBWmfF+BdotI00ruxJIMrIo3OFml9YLU6FYELu1ynj0oGtDPE6qOLSfAxfWbeSsR9+ZE7gyqaFv3yTC5ei+PTM/vxwdyqU0fmS4UW0ssKZstEmU+LXqUa17/Z4a8ySltq7nroL0qxwo9eDtwSrJR1czsiCtt/wT34u92ubAC3CHZPSSgin4MquFt0ee3E4KWP0+g0oJU4jlS6S2b0GtJCo9CqiZE4+gyUsdMv5M04Twhmayc1/3JBC8vSaOmr20XXQimO7DldvKGDlZzyqa5N4tGzw2/H8r6DXPyuqp7iJl0t+SFRsIo2APBj0WLgpatHabii14aBAMwHSllsUVd+XCK+2l2Ilab+YR7dP1jxR0GwZg+f8FM4iJt3/JnJnab+esyqEya45VZm0ztFezqykATgBW8M3fD/+fSwYsz2sDAt19f531OaXkbTXoQg==
  template:
    metadata:
      creationTimestamp: null
      name: openai-secret
      namespace: llm
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cors-secret
  namespace: llm
spec:
  encryptedData:
    cors-secret: AgB8bL1snyzscjQSnyUj+xLGvZOhXcsjr+0E2lNNEwsbWaqfk/DyffamgnBuKALf/OnOjQ/272ju+JA+TWooMI3d50XKhKqZxaYJhK5WfSGbhmscSofNMOZBjnnIsNaF9X4j6Ky26AEF2RSPUwAlNcT4+rN2xYetXSMMNNU754GCOuu1eN09hKH2ioFodPhs2ABjTnq2U0rUd/04Hja3j1Wmv14Va6GE3NokS0IIR+3tIHFQrAuFMsH04Hsc+6IulKzq8jYEjvPxVlh3M7kwH/bLId6XlTU6YW1BnFLBPVlS39jmlGirJP/+NWg37boNM10QUujy1xIpBspJR7QR6cP9l/5EO0WE1IVidJtvljlAf1dUGQlzVy9WjuuGNcxeYYEdsgZEpJZj4f+A8qVgkwZ51E0wTS6vL5H/B1Xcf6x2Msr00Sej7KgaxWCNF5uLQiy+UnQlUMCY+zvDCSQbzsBiguOHJ6dagasLI2NM/0ynD+o86P/stYJmU2zDZ8z8QnGEUEmEMOdURYsLgnnG5OCcERQpzbsB1Og9MJGFYpMISvkUK0SEUyCLtRWLhAYgO1dKbaZiboVRgRz6hq0c1JQf2ggxaL1nwxngivHB2Yl6bOSQROjwPY/C5Sksc+ChdqvqFBmKcTWB9maaL/760zc4k644pw+/eMf0fpTeGV+j7kbgbEROgMLFgPzpHYJBe2Ni2OXFhKrY3C+Q1O0=
  template:
    metadata:
      creationTimestamp: null
      name: cors-secret
      namespace: llm

