apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staycation
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: matthewpsimons.com
      http:
        paths:
          - path: "/staycation"
            pathType: Prefix
            backend:
              service:
                name: staycation
                port:
                  number: 80
