apiVersion: v1
kind: Service
metadata:
  name: {{ include "staycation.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "staycation.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
