apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "roll-with-matt.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: {{ include "roll-with-matt.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: {{ include "roll-with-matt.fullname" . }}
                port:
                  number: {{ .Values.service.port }}