apiVersion: v1
kind: Service
metadata:
  name: {{ include "traceroute-site.fullname" . }}
  labels:
    {{- include "traceroute-site.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "traceroute-site.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
