---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBB9Ho2e+JvoJMtAG3ipl2yJq24nYyjGllaPXt7CQ+QmQIkPjOEX6z6pp5l9roeKuwBbzt9F2BdsO9DLA6vuUjaF+8r/IM+6szYJsDfcVJuJbAf8N4GxwD9y8uE7nyL2V5gS0/BASb6wnc34MqHe3L9f/nF3wuby0uZgqvQAkoCYWypLUAVA9zaNQYBluxxvwWb0/epqThDEtqioo9caYtCrr6GHZkVElfr6d772AaJE64COSwZEGiuKhiitSDCIisIHmNCHfjfkPOGZwoDcmIGgU3T1gFupYnLcjDzaJzKtTvF0qPivwBO5U229Kf/1Pwvdj88Ug5SVXFJR8yP+f5uUu5b8c9GfkB9On3v61wz9o+Ul5RwHMqd7+tlEVG6AvaWkojtwPXZvMWmgS8oEYN5fmKC+lpUiq2dq/yIbpODD8/6QfLdaOhaJ/3Tk2W1BU6qobROwyamjPaegPJ2Rs6A0Nnf3QxxsD97BS/TmFjUP0/YGGoAKr6Q1ZAQ6OTImLTBBVJ2B8ZI2SHQOfl9UmX8pL5E9jzknkFWKyikGVDrvzqHi3fm+e8qqQlu64Mm+GgNio1KZGEu+ihIDKKaahtqVLtT0n9+ySZnQGB8QzJeXLxbjN4xjFwZiDdACIRw30DKM4PEqf7127/M7ujSlVtVkjJ5m2cSS2MKVQJOvxRI527/shg5ngR+RmcPKyIg33osBZ72yc3HK8IMoBbBHFGlND+35MFG4qqsc2nr04hz7Oi7d+b897CsTfzulh/ZskqdP/Y7ZWt9BuEhtCsamZJCT7qUvK1vR3/8lYQd+7EvjbTblBvhmRZM/DpeJYQ7iOgGj8jA9/J5aUsyQywXgcET4oCdJPxRtThY/+z9PHTp91r+XXPn8rQYQC7BRbaxM609JhyKZ/+5vVYFv3q+/VecA4DP4zMi2w0FHfjdEsorJWn9gUgbOKkr
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cloudflared
