apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "mailform.fullname" . }}-cors
  namespace: {{ .Values.namespace }}
spec:
  headers:
    accessControlAllowOriginList:
      - https://rollwithmatt.com
      - https://www.rollwithmatt.com
      - https://matthewpsimons.com
      - https://www.matthewpsimons.com
      - https://api.rollwithmatt.com
    accessControlAllowMethods:
      - GET
      - POST
      - OPTIONS
    accessControlAllowHeaders:
      - Content-Type