---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mailform-traceroute-targets
  namespace: mailform
spec:
  encryptedData:
    traceroute-alerts.json: AgBNOzKhMJ04MjnyV3wqCC4/fVLFS/qRWy39EGHsUMWMLAB7KKnq2qVRaGcWxK57nsNWBu0OL1qeuYW119y/RMGfbUSCk2TXHE8HGzs//WSaY9poUYybwCH7T+gFAOGrjOrpeu89dI2+cNy6XaMw+3msjMotUoMSgU4csbKPxIWfOyokF2VMz0ZO+WSKJMMoBOzOoIFyTrzQ2WAQ3jbXhM3DOgWYN4SrER99tmqiCAPh0gXIztO6bOyui2cVNOact72XvVClnodMHKjpEnqeJ7+ePgp75JRul2pEzADCpaFPbCK8pnDOgZ0c57zeWJTJBybXuVhtif2In1fJljqW86M0xmFoXVlTiPj9KQ2Hlrf9uWih+ZHqgJtTHZYb+kz3HBSHo5rpGjz+CvPJAzJG8iJJagKr3WiCs2E3EkV9A0lpioKfrS+oJrhjjdbtUIXcTCizXjN8Alw+mehjqx2VXAupS0GnYMq62kyv0wH77Q7UZZDUpVxZrfJmAR2ekhLsHW4ChBL5U+uooePiQKDtn+SJxTyRSnXAUNrL+iXiLWbzvcTm7eAWWJocI6oliKkc4yUCVvZxRV4gC84yE+wXA+pyyIfvJtDKXyDVd2AFIWo9AIxa6qrj/aXGlPp4wa6xnNzLS1G6PVC8PIN7aoGccsKiMttfBqcBG4zf6xJGaN/1wcrVkQraUPVcWAvueg6sYo/LwqjCDgU1qvrxRihwnRjFSdD18U16pSqisazVXuQl7lZV9TCBWM1WWUSwvYV5xEN3QKDd+RoO6qrbq/5g7PTTkJ3kdUi3nCWCxeYGuGZHbJ65Kovw5idEXfVM0hHlsagEuGopTmJdZ0IGJzvzKi/nGsDoHTooow77N06Pa3Jy/o7dQDR4AMXTR8+I80x1DI+Bgoncg1mSwh73iXkrcHwO8U4qULoX94ht5r8wum75gzIeuuRAKqEGYEVDaqEtTE3ywrWDku/B6GegSYlMKOXJVR9h9BOu2Nra+5jmUmR0NZwnUa1OL9kxrg5fQVbgbW/pipXDbSvkNKZXvhQxIgoGMIu3EV5Eixgwdi+hkdeH/zCySC9IyE+ezEoTbMcwlaHEnjaqXP9y0QTq2w6BZnpcjx7kqtJKrSVh+wCf6onTVH+U53d4PhGmv/hDqrGKrRyE9pOv8sZa1aQQ5DTJkuZPmBCcsU6WAI46X7zkRWPxeg+rgl5HYW9nnIvaaA==
  template:
    metadata:
      creationTimestamp: null
      name: mailform-traceroute-targets
      namespace: mailform
    type: Opaque

---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traceroute-alert-client
  namespace: mailform
spec:
  encryptedData:
    bearer-token: AgBq4bfx4gMrtiIPVmPHLy/zH2s6Qtpbs2+oyBlwjX8Vo8uvFurHW0TUQ4S0SLpctpULweFmmz9KqOkIf/qLTTKcewSiDxQGoUnkmGnH7noWU/5UiJi2rn7ebz8Gf7MWjjYvhvaljBP3EOqWIFilganEIFprqr7BTYDkGua339cRigaG+9B0T/U+Dum/F70RLCSQ/NleuvDMYgNlzxd6QuV56EvZoTisbwF8BriIPZhVDc78S1J80GAwEhYbtDia4I9lqrODPVKGA2Cf5GdmoPU64PosdW48+dZUzemmcYRvdSlGgqE+xcuGPiJ3mnlrx9q/dNB0Cden79m1l3iAy5NFH66YL59COHJDAbVGFnFmRvbJOfU5jqNe5NYKlpjXry6vfnVAw3UztpY21jzQLEfjqpejsnZbU0AfvHRvs3WbitCS01QaTZP3B5wJgla+FjbMvdpTmkKyxIAXmEvaK232V8zB2UMq8VWz00KV0y7joD30h4akdpv8QGICppsAq7/y56COUuwFxIurAk4EynYQYeNQiAlw97vhFS9ZdndZNnkyn5Q7z4ghjCXBhD/UcPtbA3gLRdodXn5u98OUFOnTtWE2SmnL4q/ju+HwfCHw7R2HmpTGsBSvLVJC1orORJzwPkp4+2pbi9ikTuQMcRzHTKICeHHgscLCP2kxbV/MrBSyQa4POPSNOkbfeWl0W5e8XHPQjIpaHKCWZ6Dp0Ly4Wyf9SQ08qO/T/dO+GYPGlRsUYE8yDXXNI7/Rd7ttUUPydrUZiVEZdBbHhhg7A8d/
    endpoint: AgCiosNxgMPFXPP54789b0YR3mG5lQ48wy8fSscg7o8SK2Nt3IA98+ik/r2N9ExR2ioc69ABQD2g0k4IMLcYJ/UOazrTUUkA/U/kph/DNV7oWwGXf9VBpDoQhcDDfp73FVe3tPAfj6OSP4OC9e92CuVNnsdwGjD6xujTzN+0gTvG8IrA5rOlXs4ixIJYGPqPNpzJF6rA7w1tMvKAF9eyr5PKyjfaUWGbuJHLpBn+eiQFEv66b9W8xVmLFs5kSlVkuy7g2cgcwilDdGU9cVOwzD1b0AxU4NZjVtcxzsANZlYgDxXA7wsIrdg+MazR8mW/1Y5YhNmcG72ZdTfbMyXcKUGfbARzBTXX5NacVbnYggag5ZvXNZ7Gbp7s25asyF33tk10cTzTnda1enau8qnq7rse4AsxvZQMfp2tVNx/fm4sS/S9nwL0dZMGjI6dwGunlgxgXWM34KXvciIY9UGysGNIXn+OFKAOcCmg95UxWjd22WLXBLsowvSWBjuGt7VznefyctJTGtau/IvwWWjCvvDkAifcatJWd9zgMYjxXVqM5sK5u2wwemeol9g5fN57yBJxppS3VH9WxRpmvcqPyEwnjDIe40BewqqXYuKYvWzuaCv1CO8FPuE+R1/jqXNkIWJcuorZ8R+JOEQXRLJfefCvQ+vcThsbTPa27MZt2ItfjfnRXq8wuEVWJb2fLCTCew7d8l3owQnSaYquAv40bCm+pBYW2uiaHBkzJ1tH5m262vBmF5zHkbpgGFFWa49FmmPgsmRIfG49kev5U1qD8T9vOw==
  template:
    metadata:
      creationTimestamp: null
      name: traceroute-alert-client
      namespace: mailform
    type: Opaque

