apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAdp6QXE/EaKTyWhPC5ZJPwE3nggK7sOk1tNFoX8ZEiukG7g3iIRVkmOzxY7HC6ZfkdfY6AaNrHrW73pK/g4dnpA97bek5ETIyovTTOXKQkFJAXMJI2053hxyk0coL+K9D3q0X8v69BMk6qtjrdILJCGFNH3hQAyN0ebOqMzp5g9jIowhpEsRRYt7Z9tIBzkp/2HyjV3/qRNcN0T5aysVqHuAmrnZ+QX1fam5WQNaRVfoyxWRtXOZ/W8bBKxw0DyUI02iRWXh49JKlLxYseYN+JaVY2KTPHYh9crdb1ItO9ba0H97GH4tBTgWGYWGDJskY1y7aT7JFwQNpHK7QubgokPdwliJo5sGl0m1L8wiJRj9s6z/6oX0/gkRZxK0OEHGfCmmNXeRfLDohgy9nj0G9VxsNQGjASUYEv0l8nm0HGiFQcKvZyR9C0QY+BID0zTZncXm6R0S/U8jnd4logyu7G0PGLyBF4mPLWZ4mG8ydpn4BEzGYIplnOxJeVDfsCwN+k5oXSlKWbjf1Jx9KpAsKJIf3a51PkRuZqw5O5rq4oqV1jMrJfEigOsY0mYKz58/rq9RpLJvWtE+hdVjuA30Bj0mGiqoKw2UMZznXAnHNucaluMhUvNJyyK88fXBFZ0opwELS25NEnMqpnv7bdS++PAWS8t7dYyX/uYuiltPNFjifWxHPn/SXtUWZaHW5ZtSGufBx297bJZTXdOJyTYCqoX+IC3UuE/UTYPhTAEQ==
    admin-user: AgB4QIKLDu4BNNTmpAj6UQ1ihE0wha+bg49eFVK/sbloPm0psCm66QupBYvOq+C9IdmBC0BdRRwuahXxEZSvNaGIsYqsxG90MSNAgY4fElQ9NCU2FfC/jCRugqQTl5nK8yRHyT532ZAz0jV7Qm4LOI6kTqCeQ3sud8nI6qFDycxZ5hQudQB2ofBF13I/Uu4Eau5mQHd/enWFc8uHgdvqn1VVBIMiJ/s5NYrcjIrisuYXQrF6HFmpEkUqOHVp2zz4c8EHfGzKfK3B4dJX04VFBCiH2+IN6uKn15+fjozwQllvdqQkPtYY61ZAbD1yVxRGPkcErwnCFD9I1N5P/oltQ+9ErVsmYU/nOQX/RjL+LxnqGHZ5/w0zsdiJiGW2+DkJ7f2wQcX97ec+WBziaBuC7/udE1SfKz3BeJUwKJM75sHNxLvvA2J/IEwO3G/6fj5WwereREUZe+s4DAV9bqgkfHHp2AnfqPRZMWVeT3nqGQPx9QlJ3PAfw4PqnEdoUEqFq2US6fjdxbQfbuFJaPwjVQq80e+H0ju3s7Jd+olNSl5x5VNIlf/oOpAsFHvV0OUTWYB9BHpuq83GU4o66ScYQN9IfaFivstgBbWbx3AkZY4aBp9Enozf5MvUFPHFXrcB7bI/Vz77oPBpfGkcEM0ARe62TLDfNz2ak8vCqI4hmcWVk02wN9WYre2JPb1EgrABvzFRoBvzVA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
