---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ntfy-alertmanager
  namespace: monitoring
spec:
  encryptedData:
    token: AgCjWIpgRkOXKpI/iYIc7VjuxX/PkJLDwkLgcUm/T1l8kwJdbNcTvW2U8UyV8x4EpBovFYxyakYLzmCR8NpSqXaVCuCgfLLAjXIwHhyA26oErXxlHo0h0fWFt8xg9DJlycmIYH2h7kIPAy5Blls67A6icZAlqQs5n3PqHxmsNd5mOs68uN4aoq8iti/IL6wy/76yDcqJ2dS3DK+VElYOAaSBWgXIOTOLZ4iU5zKukgr0K1KiWs1xPvA56GoJnTv14WFlzvNiZ9LGi5j01w0mbXOa9MrAOtxGaTpoVAzdT2QYTvxOWqIGzXpksfOcZyGEL4ZA0UjCPtrhRLvkUpJ9FHeBVkvQT0aSOTgkJA6E8loyhJNtkdPIqaLCAu6IqPLy8HPDQbP8n6hio8iNai/X3eigJ3N1xzAuO0vE8LHegCOx6wevt8IYiVIJaZ/tKN3i5BMU7CnFCFxsireOE8iQTrFdoNWn3mcvEpErR/X3aMFvZbek5q7KfP80AqWKnVofpz9wvSGNY7Rad5JYGAftveU+Iws+7IOJLYhB6lETBDtgmml5qNeTVbERXU+n9ir5WAdDfPz0M5d5pUutxo2wyt0D5QgdNMHIBLE9lRO6/88zvYe8i91WuZWDlX0hT50orhGwZJ4cKhUFloC1VvlR68nXN7TqGaqmplqTy9fDzh6aZwzlStb/0JDhifpYEBcBUIRW+87Bd1P4wgLboQQJ4fWjrcHpUdLOUWjw9f1H7fKHyw==
  template:
    metadata:
      creationTimestamp: null
      name: ntfy-alertmanager
      namespace: monitoring
