apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: radarr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`radarr.int.matthewpsimons.com`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
