apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-applicationset-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-applicationset-controller
    spec:
      serviceAccountName: argocd-applicationset-controller
      containers:
        - name: argocd-applicationset-controller
          image: quay.io/argoproj/argocd:v2.13.2
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_ADMIN
          args:
            - "argocd-applicationset-controller"
          env:
            - name: ARGOCD_REPO_SERVER
              value: argocd-repo-server:8081
            - name: ARGOCD_API_SERVER
              value: argocd-server:443
            - name: ARGOCD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace