apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-applicationset-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-applicationset-controller
    spec:
      containers:
        - name: argocd-applicationset-controller
          image:  argoproj/argocd-applicationset-controller:stable
          securityContext:
            allowPrivilegeEscalation: {{ .Values.applicationSetController.allowPrivilegeEscalation }}
            capabilities:
              add:
                - NET_ADMIN
