apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-password
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgA40H2Svs/mnDql8C55gzuzcOa+PeDn1YvMH00xnAulsZIz6e1/5cUeW0NzEO+zNyjhguQrdRMZpV6Fmdllg3ZqFplcyCfxWxMgsxtyxskLAfGQ2c5xk3ImfE0JNFitjNFTcgTVNAwybvhUcJyaJagBqsXPsHC2oFkHr/yh6baXPBUFbXg6/vtRu091AqTJ9zA0gOW1pOqj1ehYAvaNjryLwL0KR7vVICwrRPqZbLo6vd7ifNyi6Lcw2Y7J8Fgw6c1IBy4PT96yYwpwh/SKesfZVllgexCtS7uR8rF5b+/hGkjsbqDfyAHCJhGlluxYlyjj6e7+YmOfjlLcZ3K0u1oqaB9FYwoE6vEslnSIY/IwjceWES+l/3Y6Xbu70T7N28OCKYwGA/gsksMab4nklEvkaPDSw9GclhfboHfEE6xp1mew5PjgXaE25mhjhy4TElPIfcSeCj8LrjrjsJC9XFhZ3YgcFV1Wv2nahvVvaXL1eJ4ce6OdM1QFxMZYCALpC/W0IOX3gtutaA3aHzfINesM7uieboR/HKEzNYjOqwu9TMAfDkxkVJm9NWvkT4lWFJOW5SuC2Bb2YBx4If9VnwexJMsR1igrjDKH0Ag6HjqQYTGXVA9oPkS+mM73Gm9Lcs4L6CWt/DppLxP02RB3cJjQKQHfaAlA4+epmiomQzGgR9LnJVp8PIiSQuf5F8eXiI5zqMQM/Fnh2n9L
  template:
    metadata:
      creationTimestamp: null
      name: admin-password
      namespace: argocd