apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-password
  namespace: default
spec:
  encryptedData:
    password: AgBJ+jnBJAleFohbrPPZTwlANsnv1tDNNDzoqFM/yQnD7Jh8EVfOTWaI2FefYkTaCjC7Cuo8a6Nw+X3+Br36Uojq5xU0HW+rotZ/9Zn+x1u5hGtf8IzzkyUl9ZIEQ/TPvXIREby9q0UemmiVan8OxoGYsbPiOa+YSPuJYVk2XOVxNnnaoWFzJJlEyGzWgKCmMyECknZ3KBzInBwjW6B16NGMTcjRpP+ZQZ/PzVJi6qNElssL4rsbzY2Qk9IQvOTsBX8iawq8UAY5UPDgHxEWnO8dkWyAD7k5q8o8wviwrwRsQ+kSgBS/1Ls+SEpi7JWjjBccGpAcH1V5Nh7PquJI3Qvs7OVbTWLBjR09Do3UGuBjZ43FTxDC75tCSS7KyJ9FUu0JtI3C6qGS4lRf2bhJpz/TFg1nf2FZG4NveE1an4uGKTLhsAcjPoTYYQwZHGPXwmRZ3w3Iifsh2qFiIgt+9oQZ4MZBLGkTy1pZDl5RLhDSSwvhspu1g16tqCngCIttS8PE040aFLepGhQaicK3sv4nrDQAvqz8J6vfG9hLVfU+1RwTcjoH27BXJWp0oJACnT4US6CkAB7iGNAOV/FDFJSNOJHU//qPYEBClRMBmKyx822LUTGCSXmQaIFQ2Pz7x46tgXX5ckXeZNXd7nHGsLpvUNhoeVs7giJjY/nnDxTg8YcTYfrFtAHMdXIBEWTC8ZRJnJfElOSgug==
  template:
    metadata:
      creationTimestamp: null
      name: admin-password
      namespace: default