apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-password
  namespace: default
spec:
  encryptedData:
    password: AgBkhVuQovtGoYQphrgKARCrg97ZhCGaiqaA3Xpt97ujjUB0cCt0aMUER+Wk5PW6pON0LCh7Zt+VR1hhLMpLMCCATxsnAKtwVQn6H7ge2AsjuXCOb4Ji3fSKQ/wssaq9mTMo8QjMA2sdOuMs5UB6p8ZqQ5QghOO0Uc7RUu28si4Udd9AoakKIbQ2/j3SkcRVnrWDiPK0QMZRCrYZguo9Li0QJzy7rf4DL9mTJHsvJM5horEm8TzX1Mli9B6Mx1XFrK/iCOUuwmM+fyvIv5gpDBkbxMoTcDqW35Zbhxp0Un8UHjT/gh0GQY+kZeked3+Kg0wZVOBe1f572jQFiwN8x8wX6lbulU8g4NDgjRtIbt4BSIotgyBxRh+gC9WO8lvYdB2T/4oeWDS3ffSU+6ETr4pMx/3QOej0el3NKgpLJtRCFtSm2Q3t291OlHJhgGgvwLP9BRxudetv/0M1E0QyU/Lo2Tm75IyRt5d7KnjTOjzPIfEUm2i6UGkRn4+gE2fqDKCf8YBbmGIvtI7gaeP76h3MZjOvVv6IF/b15ZlPYHcQDdBTVBS8Gx8S2vLxSY4i6Ougnrc7JFlDcUYjsIhBz6rqKmFm5+NCeOWP8jwPAOEY2YIqCzoJ/1NDeyTj0pauYpJZOLxwfUr0Fsw47yHXtXPXpq6FA3fZHQiCQTY/IYLIXBv0/HAuLW/IWpsMP8OyAOPEyPD/YaPnaA==
  template:
    metadata:
      creationTimestamp: null
      name: admin-password
      namespace: default