apiVersion: v1
kind: Secret
metadata:
  name: argocd-initial-admin-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-initial-admin-secret
    app.kubernetes.io/part-of: argocd
stringData:
  password: {{ .Values.sealedSecret.adminPassword }}
