apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: ntfy
spec:
  replicas: 1
  strategy: { type: Recreate }
  selector:
    matchLabels: { app: ntfy }
  template:
    metadata:
      labels: { app: ntfy }
    spec:
      containers:
        - name: ntfy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["serve"]
          ports:
            - { name: http, containerPort: 80 }
          readinessProbe:
            httpGet: { path: /v1/health, port: http }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /v1/health, port: http }
            periodSeconds: 30
          volumeMounts:
            - { name: config, mountPath: /etc/ntfy, readOnly: true }
            - { name: data, mountPath: /var/cache/ntfy, subPath: cache }
            - { name: data, mountPath: /var/lib/ntfy, subPath: lib }
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap: { name: ntfy-config }
        - name: data
          persistentVolumeClaim: { claimName: ntfy-data }
