apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy
  namespace: ntfy
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.host }}`)
      kind: Rule
      services:
        - name: ntfy
          port: 80
