apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-router-config
  namespace: webhook-router
data:
  PORT: "8080"
  LOG_LEVEL: "info"
  BASE_DOMAIN: "matthewpsimons.com"
  RABBITMQ_ADDRESS: "192.168.2.16"
  RABBITMQ_PORT: "5672"
  RABBITMQ_EXCHANGE: "botbot"
  RABBITMQ_COOKIE: ""