apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-credentials
  namespace: webhook-router
spec:
  encryptedData:
    password: AgBVRsGNIa5EpGImHOQpiwHUAVlbWxea6L2H2qxLf0ETDhean4voFEUElDA0Rd5KgFcck+LMfJinv4YOr9wwdPkXromJqhYQNBW2SguJcTrIKu0vnTWHNTdycm/ErcxirNWKQNLVdaPqgcuHtrkKUvogzROhDLKf0VXlz3Nf+wv1XGiPgmN+XXSicLCBibH2AQrRAxG6hb/SiVr+8gI/Ar+JjTbdq+3vADdPAGf9a4YpzxEcLgYLpt7GOnwZBAQ3iC4z4+SFon+WYxMJt0F6Rtt+LKXmqJW1x14q0y11umCgpqVJRhaAqvfbuSMruYpxEpAr87uB1snP8i5/pRfSvGTQAkm7IEXp9O1oZiMTE7qAlOI0DJ7WT+2McgAn/rjW/3M449FcsQtmu3CSlWliTR+OnEEuKeG6fcVxd8bJCga+/frMdY2GpDl+jzt5XApgEy0pOE4SYlFST2CSXOhrOS6KpAWkinBEkIqSn974B+SZ5AXRkIDbukDour7P6CL5dfNX5Ayc5fY0tg2j+NTQYzJ6hF/13R78bvUwj/di8tdBmWe5NFns4ZYCZXtgzwh8+2F7thwx+XaeKtnnzs0wTK9qkUJRCCGhn3bNsceUxrF6gOGbmj373dXbFqFuXvSZYoY44ywlD7zkxDSTQZoNqDOcXSODYtSfWZRIlifI9Ya4ytiQ3m806UgwC5xMlGIqtXmJwGCR7bA3uqy+VyXGV+UpeAo1YrX0+Ni76xvVaFooA7Bm7oXsDlsISgTF8A==
    username: AgCQL5qJPjNO/T1tzKGDf+3F0tCLw2O4dH/JCFu2JcSoHN3CK5gEMM1sUAqRsU/x0X5tdGLrZVuFCRX6MS2RZvFkN/jnRDCTTto8Nu3pJluXAmMEefQFxqBBn8XyEPM3hI1DOkGnwW/hO3UKILd+rvTVG0c5R9gOciH1QsbK4rPD7Q863Dau0YNkabYbybEhjfDyt/SMGHcjjRh+zwYZhiQy3ryQd+rX13abLE6iFbtqG2RnkfRA42AFxN/hnSxAYWYTXahfuzyDkf0or6vrNTpbLbgl4VruLBltEXOTUjFxM0w5FJvsNn8KQrj7agOt9KfxYCO/o0gEwkOfI3B9BRk3rjhI7HqUaRl0YzGOXLaA9mSBcbLKJ4F8OCF4p1RKslqtwzLCqJpWuXop4KfuaMhvkewke3jr50W1eKKGebUgLprXu877Z6ki215QFxlXIvgsB/LACE+Ylm7gsXohoD6AHvuuK5W0f4v3HxsAhIZ2Yy+IAsYkXE/JX8u9jv2qV9JkkOtZzd6EHB7LFTRBeAemUYWkpmv0c+lBhRWhu15LshgsgvtaGCJKqFiXWHAsdwwRKjnoTjdp0auFUguSFneJcUB75SnKFFPZClmzw060J0VM6WOsTALwkKE8V+nHl7Ri1nwG5whwyx6ancBzAbh92NJPTIU2y5IsJO7NohXkuCDjivakH6rML1zrvqPk1/Z8sPf/lw==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-credentials
      namespace: webhook-router
