apiVersion: v1
kind: Service
metadata:
  name: webhook-router
  namespace: webhook-router
spec:
  selector:
    app: webhook-router
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP