apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret
  namespace: webhook-router
spec:
  encryptedData:
    secret: AgASxMJWOPjV7XiW3F557Gc7HYnWJWLYMw9/shxqHw6nUWx21KAVrSXE9tKnS7JVWo1RZI6Fd2YHN0D/RAgYKB8jDrN3Tq+0rGg/dStIcicOlEiQNa+aX3IX3mQQPR1gZBZOhP6aUEwujuuwdz2n5Xd/T9tWJASXhAw2YwI0XUZe649opUHc+ZaqgELo+x2VK8GC6fcXavidMCA6023XXGoaoSyhxdYH1x6lBwmhGPfcXYAVBK+sTX91XCiTLV0m69WO24wLwWq8lsxTKxpzPLvz4itW/dHHKWFfFrONDYBvXb2PrLMbsMJJJK9w/UGzuPIg1zged3NEYkCPNSStEXBxxby3fVZfz+RGF9te30cqDH4Q3BOxKRcyj6pNLbqF8tQ4oGlFYv6cLgyEMcY9pxsbhg5ucEHA9jzExUXQydyTh8YVSIUpVa046IVUBovb9qOFzpPNYtCnxWHLgFomobNL39MYppt9ea3rAg70QgXi7M0otUAGMuvpY6cWHzrIl0RyWS8yu+VYLiQO5qMYSm/DKYKtFGhxyNLKk9qD3f7uiJD0AoQ+sC2q9OkHeJ77GnId7goGHF50zxBtN55S9hEF7Bmk1XIfZQSSlnCsfOdrUBPNm6n9OV/izuBZ+uxlpcn40vt9OCu1+RmwlITXXMmvc6tC6OXg8ocxOHtB85KXv8D1tq5DF7uGSDmbJVb4zbsLUpsdmgkFf9K6FfXEdG/F91e0vlHd+0M=
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret
      namespace: webhook-router
