apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik
      volumes:
        - name: acme-storage
          persistentVolumeClaim:
            claimName: traefik-acme-pvc
      containers:
        - name: traefik
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--accesslog=true"
            - "--api.insecure=true"
            - "--api.dashboard=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.traefik.address=:8080"
            - "--providers.kubernetescrd"
            - "--providers.kubernetescrd.namespaces="
            - "--providers.kubernetesingress"
            - "--providers.kubernetesingress.namespaces="
            - "--certificatesresolvers.letsencrypt.acme.email={{ .Values.certificatesResolvers.letsencrypt.acme.email }}"
            - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.httpChallenge.entryPoint=web"
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
          volumeMounts:
            - name: acme-storage
              mountPath: /data
